version: 1.0.{build}
image: Visual Studio 2017

environment:
  DOCKER_USER:
    secure: dk51uz48LGEmvYMmD3Fygg==
  DOCKER_PASS:
    secure: 3eVMIsBLAepb3U5TfKWqXQ==

build_script:
  - ps: .\Build.ps1

deploy_script:
  - ps: |
        Push-Location .\src
          if (!$env:APPVEYOR_PULL_REQUEST_NUMBER -and (($env:APPVEYOR_REPO_BRANCH -eq "master") -and $env:APPVEYOR_REPO_TAG))
          {
            # login and push to docker for tag build on master branch
            docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"
            docker push herbertbodner/wacore.talenthunter.api:$env:APPVEYOR_REPO_TAG_NAME
          }
        Pop-Location